#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders vim ranger curlwttr bottom
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && eww close-all && firefox --new-window &

elif [[ "$1" == "--tg" ]]; then
	close_dash && telegram-desktop &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--tr" ]]; then
	close_dash && alacritty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--ge" ]]; then
	close_dash && geany &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--vb" ]]; then
	close_dash && virtualbox &

elif [[ "$1" == "--mc" ]]; then
    close_dash && eww close-all && kitty --class 'kitty-float' -e mocp & 

elif [[ "$1" == "--wt" ]]; then
    close_dash && eww close-all && kitty --class 'kitty-float' --hold -e curl wttr.in & 

elif [[ "$1" == "--ra" ]]; then
    close_dash && eww close-all && kitty --class 'kitty-float' --hold -e ranger ~/ &

elif [[ "$1" == "--rst" ]]; then
    close_dash && eww close-all && i3 restart &

elif [[ "$1" == "--vi" ]]; then 
    close_dash && eww close-all && kitty --hold -e nvim

fi
